# Generated by Django 4.1.7 on 2023-12-12 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 12, 12, 15, 32, 47, 153048, tzinfo=datetime.timezone.utc), verbose_name='Date Created')),
            ],
        ),
    ]
