# Generated by Django 4.1.7 on 2023-12-13 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_fun', '0003_alter_subscribeduser_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 12, 13, 15, 17, 57, 443012, tzinfo=datetime.timezone.utc), verbose_name='Date Created')),
            ],
        ),
        migrations.AlterField(
            model_name='subscribeduser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 13, 15, 17, 57, 442193, tzinfo=datetime.timezone.utc), verbose_name='Date Created'),
        ),
    ]
